# Run the 'make test' command for prs + merges to master, via github actions

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install lcov
        run: |
          # fetch lcov archive from github
          LCOV_VERSION=1.16
          wget https://github.com/linux-test-project/lcov/archive/refs/tags/v${LCOV_VERSION}.zip
          unzip v${LCOV_VERSION}.zip
          cd lcov-${LCOV_VERSION}
          sudo make install
          lcov --version
          genhtml --version

      - name: Run test
        run: |
          make test
